### ISSUE TITLE
Needed to add MVVM Light to the client

### ISSUE THREAD

**Issue by zelmon64** [RiftCat/vridge-api#1]
After installing `NetMQ `and `Newtonsof.Json` through NuGet the solution wouldn't build and complained about `GalaSoft.MvvmLight`. This was the first time I've ever used NuGet but I found I could also install MvvmLight by right-clicking on "References" in the solution explorer. It was already installed under `VRE.Vridge.API.DesktopTester` so I added it to `VRE.Vridge.API.Client` and then it built without complaint.

I think it might be good to add MvvmLight to the [Requirements for this example](https://github.com/RiftCat/vridge-api#requirements-for-this-example) section of the README so that other people don't get caught out by it (and perhaps a little instruction on how to install them with NuGet).

**Comment by balukin** [comment]
Right, MVVM Light was supposed to be auto-restored with NuGet in WPF example project but it shouldn't be necessary for Client/structs project to build. I'll update readme.
