### ISSUE TITLE
Controller not recognised as Hand controller

### ISSUE THREAD

**Issue by TheKayneGame** [RiftCat/vridge-api#19]
When emulating two controllers only one of them is recognised as a hand controller. which means only one will be used in games and visible in SteamVR Home.
One Of the controllers has the ID 0 and the other has the ID 1. i doubt that has any effect on whether it will be registerd as hand controller or not. 
I do have a picture as proof of my problem.
![chrome_2019-01-29_23-38-51](https://user-images.githubusercontent.com/5954012/51945620-81190f00-241f-11e9-86ee-ddf386816e26.png)

**Comment by balukin** [comment]
In next update you can mark controllers are left/right which allows them to be correctly recognized in SteamVr. 

It's currently in beta testing (available through Riftcat PC config). Updated .proto and C#/Java model classes are in [v3.1 branch](https://github.com/RiftCat/vridge-api/tree/v3.1). It will be merged in next few days along with Riftcat/Vridge v2.3 patch release.

There are some changes to the protocol but everything should be mostly backward-compatible. OrientationMatrix in Controller struct is becoming deprecated but it should still work.

**Comment by balukin** [comment]
Closing - the preview v3.1 branch has been merged into master.
