### ISSUE TITLE
Pitch and Roll axis problem in Desktop example app.

### ISSUE THREAD

**Issue by Desm0nt** [RiftCat/vridge-api#3]
Good Day!

Desktop client example app have a problem with Pitch and Roll axis (or probably with all axis) for head and controller rotating (when real phone tracking work fine).  This problem similar to vridge freetrack implementation problem (report #11641). 

Because my English is bad, I can't fully discribe the problem. But I made a video with several demos (phone head rotation, head rotation emulation from app, and controller rotation emulation). I hope it can be useful.

[https://www.youtube.com/watch?v=e6rS-2XVjgk](https://www.youtube.com/watch?v=e6rS-2XVjgk)

**Comment by balukin** [comment]
Thanks for the video and detailed description! We'll check it next week and update you on our findings.

**Comment by lonqq** [comment]
Hello,
We identified the problem and are currently working on it.

**Comment by lonqq** [comment]
We've published an update with this fix on beta channel.
