### ISSUE TITLE
Controller API - detail values of Trigger and Axis0,1

### ISSUE THREAD

**Issue by mungewell** [RiftCat/vridge-api#8]
Hi,
These items are defined (or rather encoded as) Floats,

Please confirm the allowable range, ie what SteamVR is expecting...
Simon.

**Comment by lonqq** [comment]
Hello,
Expected range for those variables is the same as in SteamVR. You can check it here: https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L869 
Axis 0 is a trackpad, Axis 1 a Trigger and Axis 2 a Joystick (I'm not sure if we put this information somewhere).
